apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: openvino-model-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: openvino-model-server
    app.kubernetes.io/part-of: openvino
  name: openvino-model-server
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: openvino-model-server
status:
  loadBalancer: {}
