apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: src-openvinomodelserver
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/openvino/src-openvinomodelserver@sha256:99bcf33aa1e4b52128cfd3ea75dfb4b3a99d9d2a22e24a5e52c99423b74809d3
        name: my-python
        resources: {}
status: {}
