apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: client-openvinomodelserver
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: client-openvinomodelserver
    app.kubernetes.io/part-of: openvino
  name: client-openvinomodelserver
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: client-openvinomodelserver
status:
  loadBalancer: {}
