apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demos-openvinomodelserver
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demos-openvinomodelserver
    app.kubernetes.io/part-of: openvino
  name: demos-openvinomodelserver
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: demos-openvinomodelserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: demos-openvinomodelserver
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/openvino/demos-openvinomodelserver@sha256:efd6029b71952bb08d0e39de4a1b31db9a267d20dfbc8c1c5ec54e692d91ff09
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
